[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[headers]]
  for = "/views/*"
  [headers.values]
    Content-Type = "text/html"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/js/*"
  [headers.values]
    Content-Type = "application/javascript"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/css/*"
  [headers.values]
    Content-Type = "text/css"
    Access-Control-Allow-Origin = "*"
